on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

name: Test and Build Application

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    container: golang:1.20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Get values for cache paths to be used in later steps
      - name: Go Cache Paths
        id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Run Test
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out

      - name: Build all binaries
        run: CGO_ENABLED=0 go build -buildvcs=false -ldflags "-w -s" -o build/bin/linkgen ./cmd/linkgen

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: bins
          path: build/bin